### PR TITLE
Automatic process prioritization for improved desktop responsiveness

### PR DESCRIPTION
**Pull request by mmstick**
- Adds a Dbus method `SetForegroundProcess` to enable the window manager to signal the daemon to prioritize the actively-interacted process
    - The PID given will be assigned a `-5` priority
    - When another PID is given, the previous PID is reassigned to `5`.
    - An accompanying pop-shell PR will use this method when a window is focused
- Adds a future service which scans `/proc` and changes the priorities of processes automatically once per minute (takes about 5ms per run).
    - Feature is only enabled when the `SetForegroundProcess` DBus method is called by pop-shell.
    - Kernel processes, such as `irq/{num}` and `kworker/{num}`, are left untouched
        - These are filtered by checking if `/proc/{pid}/exe` exists
    - Processes that lack a priority (priority `0`) are lowered to `5`
        - To prevent pulseaudio, pipewire, and other important self-prioritized services from being touched
    - Known good desktop processes, like `Xorg` and `gnome-shell`, are raised to `-5`.
        - `gnome-shell` spawns applications in its own process group with the same priority, but subsequent iterations will change them to `5` on the next scan
    - Known bad processes, like `rustc` and `gcc`, are lowered to `15`.

### CODE REVIEW

**Comment by bflanagin** [comment]
The changes are working as expect and in some cases you can see an improvement in responsiveness. However, we have seen some applications (specifically those that have their own background processes) see a degradation in speed.  Blender,Steam (Most notably Steam VR),Gimp,Phoronix test suite.

Would it be possible in a future PR to add the ability for users to set performance levels of these special case applications via UI? Or at the very least create a config file that is read by the service so that we can add and tweak the settings more easily. I think the defaults are good, but I could imagine it being a mess if we have to continually add applications.

**Comment by mmstick** [comment]
I'll implement a config format before we merge. And I'll also look into a way to prioritize dependent processes of the prioritized process to fix the applications mentioned.

**Comment by mmstick** [comment]
Default configuration files will now be placed into `/usr/share/system76-scheduler/`, and all dependents of a foreground process are now tracked down and assigned priority as well.

**Comment by bflanagin** [comment]
I've been testing this now on several system. The recent changes have made things respond more in the  way I was expecting. 

I have noticed that the programs set in  `/usr/share/system76-schdeduler/assignments/default.ron` aren't receiving or at least aren't retaining their nice level, or possibly they are losing the -5 and becoming 5 at some point during general computer use. (I haven't been able to catch them at -5 yet. I don't believe this is desired behavior. Also I tried to add a new application to the list of high priority assignments and it doesn't receive the desired nice level either. 

I 95% sure this was working in the previous version, but I was more concerned about general use gotcha's than those specific applications.

**Comment by mmstick** [comment]
@bflanagin There was a typo in the config causing a syntax error. A missing `]`. It should be good now

```
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: loading values from "/usr/share/system76-scheduler/assignments/default.ron"
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting Xorg with priority -5
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting gnome-shell with priority -5
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting kwin with priority -5
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting gcc with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting c++ with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting cargo with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting make with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting rustc with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting g++ with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting clang with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting cpp with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: inserting lld with priority 19
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: [src/config.rs:71] assignments = {
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "Xorg": -5,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "c++": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "cargo": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "clang": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "cpp": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "g++": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "gcc": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "gnome-shell": -5,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "kwin": -5,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "lld": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "make": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]:     "rustc": 19,
Jan 30 18:43:02 gaze15 system76-scheduler[1017187]: }
```

**Comment by bflanagin** [comment]
Heh, I should have noticed that @mmstick

**Review by bflanagin — APPROVED** [review]
Latest version works as expected. Users can set custom nice levels and the applications will be executed with those levels. Either by creating a separate .ron file or by editing the default file.

**Comment by 13r0ck** [comment]
@leviport should David write docs for the config for this?

**Pull request merged**
