### PR TITLE
feat: Apply priority in realtime if bpfcc-tools is installed

### PR DESCRIPTION
**Pull request by mmstick**
The `bpfcc-tools` package contains an `execsnoop-bpfcc` binary which prints processes and their PIDs as they are created in realtime by the kernel. This change will spawn a thread if that command is found, and stream the output to the daemon. This makes it possible to watch for processes being created and applying those priorities immediately. Which is useful for resource-heavy tasks that are short-lived, such as dpkg, flatpak, and gcc.

Without this, the only way to gain knowledge of new processes is to periodically scan all of the directories in `/proc`, which isn't very efficient. The current behavior only applies priorities once every 60s, causing an up-to-60s delay for the priority adjustment of a new process.

### CODE REVIEW

**Comment by KyleGospo** [comment]
Would be nice if the path to `execsnoop-bpfcc` was configurable in some way. RHEL distros for instance would need to execute `/usr/share/bcc/tools/execsnoop`, but I understand if that's outside of scope. If you can point me to a way you'd like said configuration to work I'd be happy to open a PR for that specific change.

**Comment by mmstick** [comment]
I'll make it configurable at compile-time.

**Comment by jacobgkau** [comment]
6eaf4c6 shows as built, but it's not in the staging repo and attempting to build this branch locally complains about not being able to download cargo dependencies because of `--frozen`. @mmstick Do you know what's going on with it?

**Comment by mmstick** [comment]
I'm looking into it.

**Comment by mmstick** [comment]
The package builds should be fixed now, and I've added support for defining process exceptions.

**Comment by jacobgkau** [comment]
This makes custom priorities apply immediately instead of having a ~minute delay. If I remove `bpfcc-tools`, custom priorities still work, but have the delay again.

The new exception feature isn't working quite how I'd expect it to. I've tried testing with this sequence:

- Added a manual assignment of 9 for `stress`, confirmed that worked.
- Added `stress` to the exceptions list-- saw `stress` no longer get its manual assignment (as expected), but it was still assigned either `-5` or `-5` permanently, based on whether the terminal was focused when the process started.
- Added `gnome-terminal` and `gnome-terminal-server` to the exceptions because I suspected `stress` was just inheriting the terminal's niceness. I see `gnome-terminal-server` get a niceness of 0 now, but `stress` still gets a niceness of `5` despite being on the exceptions list.
- Added `gnome-terminal-server` to the level 9 manual assignment, confirmed it still gets niceness 0 (not 5 or 9) because it's on the exceptions list; but `gnome-terminal` is still getting level 5 set despite being on the same exception list, and `gnome-terminal-server.real` also continues to get level 5 set even if I add it to the list.

This could be a bad testing method if this has to do with how gnome-terminal spawns processes, but could you confirm if this is expected behavior for the exceptions feature? I don't know why `gnome-terminal` and `gnome-terminal.real` are still getting niceness of 5 when they're on the exceptions list. (I'm also not too sure what value there is to adding e.g. PipeWire to an exceptions list rather than just giving it a manual assignment-- I guess so other audio apps can reassign it as they wish?)

**Comment by mmstick** [comment]
Checking. I may have missed a spot where the exceptions are checked.

**Review by jacobgkau — APPROVED** [review]
On 4495b2c, exceptions are working as expected. If `stress` is excepted, then it's always set to the default `0` niceness (until I adjust it myself with `renice`.)

Custom nice values are still applied immediately with `bpfcc-tools`, and after up to a minute without `bpfcc-tools`. The new `system76-scheduler daemon reload` command works to apply config changes (although it doesn't pick on on changes to the existence of `bpfcc-tools`.) Focus-based priority is still working when the process isn't excepted or manually assigned.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
