### PR TITLE
feat: Support IO priority adjustments

### LINKED ISSUE #38: Configuring `background: None` no longer leaves niceness unchanged for background processes
When setting in the config.ron
```rust
background: None
```

system76-scheduler now interprets that as a niceness of 0, instead of leaving it unchanged for background processes.
```rust
foreground: None
```
still seems to work as intended (configures it not to change priorities)

### LINKED ISSUE #39: FAHClient is listed twice in auto.ron
In `auto.ron` provided by system76-scheduler v1.1.0 `FAHClient` is listed first in low (9):

```
9: [
...
    "fwupd",
    "FAHClient",
...
```

And then in absolutely low (19):

```
19: [
    "boinc",
    "FAHClient",
    "FAHCoreWrapper",
...
```

### PR DESCRIPTION
**Pull request by mmstick**
- May now define IO priorities in the assignments config. This change is backwards compatible thanks to the `serde(untagged)` feature on enums.
- Fixes symlinks not being resolved for processes run by flatpak, so the easyeffects process installed from Flatpak will now get auto-assigned with the default config.
- Default config is updated to also adjust IO priorities
- Avoid setting background priority if config is `None`
- Allow referencing a process by the process name from `/proc/{{pid}}/status`.
- Adds Steam VR processes to default config

Closes #38 
Closes #39

### CODE REVIEW

**Comment by 13r0ck** [comment]
I think we should mention this change in the readme somewhere

**Comment by mmstick** [comment]
Good point

**Review by 13r0ck — DISMISSED** [review]
Thanks for the readme change!

**Comment by n3m0-22** [comment]
After testing with several programs I have found the following:

1. Everything is working as it was before with examples like Amsynth and Audacity in regards to priority levels.
2. Using `ionice` to check aginst PID the IO priority is now being set correctly as well.
3. Settings in `/etc/system76-scheduler/assignments/auto.ron` take precedence over `/usr/share/system76-scheduler/assignments/default.ron`.
4. Using `--ionice-class` and `--ionice-level` with `stress-ng` can temporarily take precedence over the values set in the configuration files.

I was not able to find a way to make this apply to Flatpaks, but this may be beyond what is currently possible. If that is not the case Flatpack usage should be added to the readme.

If all of this is as expected then it is ready for approval.

**Comment by mmstick** [comment]
What flatpak processes were having issues? It does seem to be working for easyeffects

**Comment by n3m0-22** [comment]
I tried a few more Flatpaks for reference, and it seems inconsistent. You're correct easyeffects works as well as slack, but mattermost, ardour, and freefilesync do not.

**Comment by mmstick** [comment]
mattermost seems to work, provided it's written as `mattermost-desktop`.

**Comment by mmstick** [comment]
Adding an improvement to better handle Ardour

**Comment by mmstick** [comment]
`ArdourGUI` as a name will now work to get the Ardour flatpak working with this

**Comment by n3m0-22** [comment]
Referring to mattermost as `mattermost-desktop` resolved the issue. Ardour works with `ArdourGUI`. FreeFileSync now works. I have tested each at different levels of priority with no problems. To be thorough I checked the Flatpaks of Atom and VSCode both work fine. I could not get the Flatpaks of Spotify, Peek, and LosslessCut to work. Also someone else will need to test SteamVR.

**Comment by n3m0-22** [comment]
Gimp and Discord Flatpaks also work, but Gimp needs to be `gimp-2.10`.

**Comment by KyleGospo** [comment]
Might be worth adding `fossilize_replay` to the lowest priority tier as well.
https://github.com/ValveSoftware/Fossilize

**Comment by n3m0-22** [comment]
This seems to solve the Flatpak issues I was seeing yesterday. Testing the rest now.

**Comment by bflanagin** [comment]
Steam VR utilities are working as expected. No regressions or performance issues using the new defaults over my personal tweaks.

**Review by n3m0-22 — APPROVED** [review]
Based on the current state of testing, it seems all issues have been resolved.

**Comment by Slackadays** [comment]
Shouldn't audio programs like Amsynth and Ardour get the RealTime classification?

**Comment by mmstick** [comment]
I'm hesitant to give realtime priority to anything by default.

**Pull request merged**
