### PR TITLE
Log an error if config parsing failed for assignment `.ron`s

### PR DESCRIPTION
**Pull request by techsy730**
See #26: this fixes the "failed to parse" situation

### CODE REVIEW

**Comment by techsy730** [comment]
Example of output on parsing failure:

```
Mar 02 12:36:11 pop-os system76-scheduler[1960289]: ERROR system76_scheduler::config: DirEntry(
Mar 02 12:36:11 pop-os system76-scheduler[1960289]:     "/etc/system76-scheduler/assignments/assignments.ron",
Mar 02 12:36:11 pop-os system76-scheduler[1960289]: ): Error { code: ExpectedArrayEnd, position: Position { line: 56, col: 5 } }
```

For an array element line that was missing a `,`

**Comment by mmstick** [comment]
Can we get an error with better formatting for human readability?

**Comment by techsy730** [comment]
Sure. But if we are going to do that I'll also update how the `config.ron` parsing error message accordingly (it is basically this logic, because I copied it from there)

**Comment by techsy730** [comment]
Ok, updated the logged message, now it looks more like

```
Mar 03 11:43:50 pop-os system76-scheduler[969336]: ERROR system76_scheduler::config: Error while reading "/etc/system76-scheduler/assignments/invalid.ron":
Mar 03 11:43:50 pop-os system76-scheduler[969336]: Error {
Mar 03 11:43:50 pop-os system76-scheduler[969336]:     code: ExpectedMap,
Mar 03 11:43:50 pop-os system76-scheduler[969336]:     position: Position {
Mar 03 11:43:50 pop-os system76-scheduler[969336]:         line: 1,
Mar 03 11:43:50 pop-os system76-scheduler[969336]:         col: 1,
Mar 03 11:43:50 pop-os system76-scheduler[969336]:     },
Mar 03 11:43:50 pop-os system76-scheduler[969336]: }
```

**Comment by techsy730** [comment]
Here is what it would like if I don't pretty print the format:
```
Mar 03 11:50:24 pop-os system76-scheduler[1019865]: ERROR system76_scheduler::config: Error while reading "/etc/system76-scheduler/assignments/invalid.ron":
Mar 03 11:50:24 pop-os system76-scheduler[1019865]: Error { code: ExpectedMap, position: Position { line: 1, col: 1 } }
```

Not sure if that looks better or worse

**Comment by mmstick** [comment]
Try this

```rs
tracing::error!(
    "{}: {} on line {}, column {}"
    path,
    why.code,
    why.position.line,
    why.position.col
);
```

**Comment by techsy730** [comment]
Oh, why didn't I think of using `why` as a struct with fields?

**Comment by techsy730** [comment]
New output

```
Mar 03 12:02:18 pop-os system76-scheduler[1112150]: ERROR system76_scheduler::config: "/etc/system76-scheduler/assignments/invalid.ron": Expected integer on line 3, column 3
```

(different `invalid.ron` this time, made it a dict, but with wrong typed keys (and other errors too)

**Review by jacobgkau — APPROVED** [review]
Before the change, invalid configuration was silently ignored. After the change, I get an error message in journalctl about the invalid configuration.

Default assignments are still working, manual assignments are still working, foreground/background config is still working for both `/usr/share` and overriding in `/etc`.

**Pull request merged**
